language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
sudo: false
cache: bundler
before_script: bundle update
script: script/cibuild
notifications:
  email: false
env:
  - JEKYLL_VERSION=tip
  - JEKYLL_VERSION=latest
